---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-hardcode
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-hardcode
  labels:
    app: cityapp-hardcode
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: cityapp-hardcode
  type: LoadBalancer
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: cityapp-hardcode
  name: cityapp-hardcode
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: cityapp-hardcode
  wildcardPolicy: None
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cityapp-hardcode
  name: cityapp-hardcode
spec:
  replicas: 1
  selector:
    app: cityapp-hardcode
  template:
    metadata:
      labels:
        app: cityapp-hardcode
    spec:
      serviceAccountName: cityapp-hardcode
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cityapp/cityapp:latest
        imagePullPolicy: Always
        name: cityapp
        env:
          - name: DBAddress
            value: "conjur-master.cyberarkdemo.local"
          - name: DBName
            value: "world"
          - name: DBPort
            value: "3306"
          - name: DBUsername
            value: "cityapp"
          - name: DBPassword
            value: "Cyberark1"
        ports:
        - containerPort: 3000
          name: http
